{
 "title": "Mikrotik monitoring",
 "description": "Mikrotik snmp monitoring (prometheus) 9.0.5",
 "tags": [
  "prometheus",
  "Mikrotik",
  "snmp",
  "snmp v3",
  "snmp_exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "Job",
    "query": {
     "query": "label_values(ifHCInOctets,  job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifHCInOctets,  instance)"
    }
   },
   {
    "name": "index",
    "query": {
     "query": "label_values(ifHighSpeed{instance='$instance'},ifIndex)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(sort(ifIndex{ifName=~'^(ether).+',instance='$instance'}) or sort(ifIndex{ifName=~'^(sfp|wlan).+',instance='$instance'}) or sort(ifIndex{ifName=~'^bridge.+',instance='$instance'}) or  sort(ifIndex{ifName!~'^(ether|bridge).+',instance='$instance'}) )"
    }
   },
   {
    "name": "desc",
    "query": {
     "query": "query_result(ifHCInOctets{ifName=\"$Interface\",instance=\"$instance\"})"
    }
   },
   {
    "name": "queuesimple_name",
    "query": {
     "query": "query_result((mtxrQueueSimplePacketsIn * on (mtxrQueueSimpleIndex) group_left(mtxrQueueSimpleName) mtxrQueueSimpleName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_name",
    "query": {
     "query": "query_result((mtxrQueueTreePackets * on (mtxrQueueTreeIndex) group_left(mtxrQueueTreeName) mtxrQueueTreeName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_parent",
    "query": {
     "query": "query_result((mtxrQueueTreeParentIndex * on (mtxrQueueTreeIndex) group_left(mtxrQueueTreeName) mtxrQueueTreeName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_flow",
    "query": {
     "query": "query_result((mtxrQueueTreeParentIndex * on (mtxrQueueTreeName) group_left(mtxrQueueTreeIndex) mtxrQueueTreeIndex{instance='$instance',}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SNMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total SNMP time (walk and processing)",
     "type": "stat",
     "description": "Total SNMP time scrape took (walk and processing)",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snmp_scrape_duration_seconds{instance='$instance'}"
      }
     ]
    },
    {
     "title": "Time SNMP walk/bulkwalk took",
     "type": "stat",
     "description": "Time SNMP walk/bulkwalk took",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snmp_scrape_walk_duration_seconds{instance='$instance'}"
      }
     ]
    },
    {
     "title": "scrape pdus returned",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snmp_scrape_pdus_returned{instance='$instance'}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance='$instance'}/100"
    }
   ]
  },
  {
   "title": "Status device",
   "type": "stat",
   "description": "The current operational state of the device described by this row of the table. A value unknown(1) indicates that the current state of the device is unknown. running(2) indicates that the device is up and running and that no unusual error conditions are known. The warning(3) state indicates that agent has been informed of an unusual error condition by the operational software (e.g., a disk device driver) but that the device is still 'operational'. An example would be a high number of soft errors on a disk. A value of testing(4), indicates that the device is not available for use because it is in the testing state. The state of down(5) is used only when the agent has been informed that the device is not available for any use.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrDeviceStatus{instance='$instance', hrDeviceIndex=\"1\"}"
    }
   ]
  },
  {
   "title": "System identity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysIdentity{instance='$instance'}",
     "legendFormat": "{{sysIdentity}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hrProcessorLoad{instance='$instance'}",
     "legendFormat": "CPU {{hrDeviceIndex}}  load"
    },
    {
     "expr": "mtxrHlTemperature{instance='$instance'}/10",
     "legendFormat": "CPU temp"
    },
    {
     "expr": "(hrStorageUsed{hrStorageIndex='65536',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='65536',instance='$instance'})",
     "legendFormat": "RAM usage"
    },
    {
     "expr": "(hrStorageUsed{hrStorageIndex='131072',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='131072',instance='$instance'})",
     "legendFormat": "System disk"
    },
    {
     "expr": "mtxrHlVoltage{instance='$instance'}/10",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "System date",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-(hrSystemDate{instance='$instance'})"
    }
   ]
  },
  {
   "title": "Device Errors",
   "type": "stat",
   "description": "The number of errors detected on this device",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrDeviceErrors{instance='$instance', hrDeviceIndex=\"1\"}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sysDescr{instance='$instance'}", "legendFormat": "{{sysDescr}}" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hrProcessorLoad{instance='$instance'})"
    }
   ]
  },
  {
   "title": "RAM load ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex='65536',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='65536',instance='$instance'})"
    }
   ]
  },
  {
   "title": "system disk load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex='131072',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='131072',instance='$instance'})"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "In - {{ifName}}"
    },
    {
     "expr": "-irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "Out - {{ifName}}"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "description": "Status link/states: The current operational state of the interface",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ifPhysAddress{instance='$instance'}"
    },
    {
     "expr": "ifOperStatus{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsRxBytes{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsTxBytes{instance='$instance'}"
    },
    { "expr": "ifSpeed{instance='$instance'}" },
    {
     "expr": "mtxrInterfaceStatsLinkDowns{instance='$instance'}"
    },
    { "expr": "ifMtu{instance='$instance'}" },
    {
     "expr": "ifType_info{instance='$instance'}"
    },
    {
     "expr": "mtxrPOEInterfaceIndex{instance='$instance'}"
    },
    { "expr": "ifAlias{instance='$instance'}" }
   ]
  },
  {
   "title": "Simple Queue (In/Out/Dropped/PCQ)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "All Simple Queue",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(irate(mtxrQueueSimpleBytesIn{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{instance='$instance'})*8 ",
       "legendFormat": "In - {{mtxrQueueSimpleName}}"
      },
      {
       "expr": "(irate(mtxrQueueSimpleBytesOut{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{instance='$instance'})*8",
       "legendFormat": "Out - {{mtxrQueueSimpleName}}"
      },
      {
       "expr": "(mtxrQueueSimplePCQQueuesIn{instance='$instance'}*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{instance='$instance'})",
       "legendFormat": "PCQ In - {{mtxrQueueSimpleName}}"
      },
      {
       "expr": "(mtxrQueueSimplePCQQueuesOut{instance='$instance'}*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{instance='$instance'})",
       "legendFormat": "PCQ Out - {{mtxrQueueSimpleName}}"
      }
     ]
    },
    {
     "title": "Queue $queuesimple_name",
     "type": "timeseries",
     "description": "Showing values > 0",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
     "repeat": "queuesimple_name",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(irate(mtxrQueueSimpleBytesIn{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name', instance='$instance'})*8",
       "legendFormat": "In"
      },
      {
       "expr": "(irate(mtxrQueueSimpleBytesOut{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name', instance='$instance'})*8",
       "legendFormat": "Out"
      },
      {
       "expr": "(irate(mtxrQueueSimpleDroppedIn{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name', instance='$instance'})",
       "legendFormat": "Dropped In"
      },
      {
       "expr": "(irate(mtxrQueueSimpleDroppedOut{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name', instance='$instance'})",
       "legendFormat": "Dropped Out "
      },
      {
       "expr": "(mtxrQueueSimplePCQQueuesIn{instance='$instance'}*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'})",
       "legendFormat": "PCQ-In"
      },
      {
       "expr": "(mtxrQueueSimplePCQQueuesOut{instance='$instance'}*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'})",
       "legendFormat": "PCQ-Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Tree Queue (Bytes/PCQ/Dropped/Packets)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "All Tree Queue",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(irate(mtxrQueueTreeHCBytes{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{instance='$instance'})*8",
       "legendFormat": "Bytes - {{mtxrQueueTreeName}}"
      },
      {
       "expr": "(irate(mtxrQueueTreePCQQueues{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{instance='$instance'})",
       "legendFormat": "PCQ - {{mtxrQueueTreeName}}"
      },
      {
       "expr": "(irate(mtxrQueueTreeDropped{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{instance='$instance'})",
       "legendFormat": "Dropped - {{mtxrQueueTreeName}}"
      },
      {
       "expr": "(irate(mtxrQueueTreePackets{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{instance='$instance'})",
       "legendFormat": "Packets - {{mtxrQueueTreeName}}"
      }
     ]
    },
    {
     "title": "Tree Queue $queuetree_name / $queuetree_parent / $queuetree_flow",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
     "repeat": "queuetree_name",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(irate(mtxrQueueTreeHCBytes{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})*8",
       "legendFormat": "Bytes"
      },
      {
       "expr": "(irate(mtxrQueueTreePCQQueues{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
       "legendFormat": "PCQ"
      },
      {
       "expr": "(irate(mtxrQueueTreeDropped{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
       "legendFormat": "Dropped"
      },
      {
       "expr": "(irate(mtxrQueueTreePackets{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
       "legendFormat": "Packets"
      }
     ]
    }
   ]
  },
  {
   "title": "*cast/Dascard/Errors/Unknown Protos/Queue length",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Interface \"$Interface\"",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 42 },
     "repeat": "Interface",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(ifHCInMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Multicast"
      },
      {
       "expr": "-irate(ifHCOutMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Multicast"
      },
      {
       "expr": "irate(ifHCInBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Broadcast"
      },
      {
       "expr": "-irate(ifHCOutBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Broadcast"
      },
      {
       "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unicast"
      },
      {
       "expr": "-irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Unicast"
      },
      {
       "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Discard"
      },
      {
       "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Discard"
      },
      {
       "expr": "irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Errors"
      },
      {
       "expr": "irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Errors"
      },
      {
       "expr": "irate(ifInUnknownProtos{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unknown Protos"
      },
      {
       "expr": "-irate(ifOutQLen{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out queue length"
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Traffic \"$Interface\"",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
     "repeat": "Interface",
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "In"
      },
      {
       "expr": "-irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "Out"
      }
     ]
    }
   ]
  }
 ]
}